import os

from dotenv import load_dotenv
from src.jobpulse.config.settings import Settings

load_dotenv(override=True)
settings = Settings()

print("==========================")
print("RUNTIME CONFIGURATION")
print("==========================")
print(f"DB_HOST (from .env): {os.environ.get('DB_HOST')}")
print(f"DB_USER (from .env): {os.environ.get('DB_USER')}")
print(f"DB_PASSWORD (from .env): {os.environ.get('DB_PASSWORD')}")
print(f"DB_NAME (from .env): {os.environ.get('DB_NAME')}")

print("\nSQLAlchemy URL Generated by Settings:")
print(settings.database_url)

print("\nTesting psycopg2 connection...")
import psycopg2

try:
    conn = psycopg2.connect(
        dbname=settings.db_name,
        user=settings.db_user,
        password=settings.db_password,
        host=settings.db_host,
        port=settings.db_port
    )
    print("✅ psycopg2 connected successfully.")
    cur = conn.cursor()
    cur.execute("SELECT current_user;")
    print(f"current_user: {cur.fetchone()[0]}")
    cur.execute("SELECT current_database();")
    print(f"current_database: {cur.fetchone()[0]}")
    conn.close()
except Exception as e:
    print(f"❌ psycopg2 connection failed: {e}")
