"""initial schema

Revision ID: 5fed874ba6ba
Revises: 
Create Date: 2026-07-08 18:57:37.101330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fed874ba6ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_dim_location_remote'), table_name='dim_location')
    op.drop_table('dim_location')
    op.drop_table('dim_skill')
    op.drop_table('dim_company')
    op.drop_index(op.f('idx_dim_date_ymd'), table_name='dim_date')
    op.drop_table('dim_date')
    op.drop_index(op.f('idx_fact_jobs_active'), table_name='fact_jobs', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_fact_jobs_company_id'), table_name='fact_jobs')
    op.drop_index(op.f('idx_fact_jobs_data_source_id'), table_name='fact_jobs')
    op.drop_index(op.f('idx_fact_jobs_date_id'), table_name='fact_jobs')
    op.drop_index(op.f('idx_fact_jobs_location_id'), table_name='fact_jobs')
    op.drop_index(op.f('idx_fact_jobs_pipeline_run_id'), table_name='fact_jobs')
    op.drop_index(op.f('idx_fact_jobs_title_salary'), table_name='fact_jobs', postgresql_include=['salary_min', 'salary_max'])
    op.drop_table('fact_jobs')
    op.drop_index(op.f('idx_bridge_skill_id'), table_name='bridge_job_skill')
    op.drop_table('bridge_job_skill')
    op.alter_column('companies', 'company_size',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Headcount band. Values: 1-10, 11-50, 51-200, 201-500, 501-1000, 1001-5000, 5001-10000, 10001+',
               existing_nullable=True)
    op.alter_column('companies', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE if manually enriched/verified against an authoritative source.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_companies_industry'), table_name='companies', postgresql_where='(industry IS NOT NULL)')
    op.create_table_comment(
        'companies',
        'Normalised employer dimension table.',
        existing_comment='Normalised employer/company dimension.',
        schema=None
    )
    op.alter_column('data_sources', 'source_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Short machine-readable key used in ETL code (e.g., 'adzuna').",
               existing_nullable=False)
    op.alter_column('data_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='When FALSE, the ETL pipeline skips this source.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('data_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'data_sources',
        'Catalog of all external job data sources.',
        existing_comment='Catalog of all external job data sources ingested by the pipeline.',
        schema=None
    )
    op.alter_column('employment_types', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_employment_types_label'), 'employment_types', type_='unique')
    op.drop_column('employment_types', 'created_at')
    op.alter_column('experience_levels', 'min_years_experience',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('experience_levels', 'max_years_experience',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('experience_levels', 'sort_order',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='Display order: 1=Entry, 2=Mid, 3=Senior, 4=Lead, 5=Executive.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('uq_experience_levels_label'), 'experience_levels', type_='unique')
    op.drop_table_comment(
        'experience_levels',
        existing_comment='Controlled vocabulary for experience/seniority level classifications.',
        schema=None
    )
    op.drop_column('experience_levels', 'created_at')
    op.alter_column('job_skills', 'is_required',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE = explicitly required; FALSE = preferred/nice-to-have.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('job_skills', 'proficiency_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Skill proficiency expectation: BEGINNER | INTERMEDIATE | ADVANCED | EXPERT.',
               existing_nullable=True)
    op.alter_column('job_skills', 'extracted_text',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Raw text fragment from posting used to identify this skill (useful for NLP training data).',
               existing_nullable=True)
    op.drop_index(op.f('ix_job_skills_required_skill_id'), table_name='job_skills', postgresql_where='(is_required = true)')
    op.create_table_comment(
        'job_skills',
        'Junction table: many-to-many relationship between jobs and skills.',
        existing_comment='Junction table resolving the many-to-many relationship between jobs and skills.',
        schema=None
    )
    op.alter_column('jobs', 'source_job_id',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Unique identifier from the originating source (API ID, URL hash). Part of the business key.',
               existing_nullable=False)
    op.alter_column('jobs', 'pipeline_run_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK to pipeline_runs. Tracks which ETL run last wrote this record.',
               existing_nullable=True)
    op.alter_column('jobs', 'job_title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Raw normalised title from the source.',
               existing_nullable=False)
    op.alter_column('jobs', 'canonical_title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment="Standardised title after ETL classification (e.g., 'Data Engineer').",
               existing_nullable=True)
    op.alter_column('jobs', 'is_remote',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE=Remote, FALSE=On-site/Hybrid, NULL=Not specified.',
               existing_nullable=True)
    op.alter_column('jobs', 'posted_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date the job went live on the source site (not ETL ingestion date).',
               existing_nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_jobs_canonical_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_remote_posted_date'), table_name='jobs', postgresql_where='(is_remote = true)')
    op.drop_index(op.f('ix_jobs_posted_date'), table_name='jobs')
    op.create_index(op.f('ix_jobs_posted_date'), 'jobs', ['posted_date'], unique=False)
    op.create_table_comment(
        'jobs',
        'Central entity. One row per unique job posting per data source.',
        existing_comment='Central entity table. One row per unique job posting per data source.',
        schema=None
    )
    op.alter_column('locations', 'state_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='ISO 3166-2 subdivision code (e.g., NY, CA).',
               existing_nullable=True)
    op.alter_column('locations', 'country_code',
               existing_type=sa.CHAR(length=2),
               type_=sa.String(length=2),
               comment=None,
               existing_comment='ISO 3166-1 alpha-2 code. Must be exactly 2 uppercase letters.',
               existing_nullable=False)
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pipeline_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Lifecycle state: RUNNING | SUCCESS | FAILED | PARTIAL.',
               existing_nullable=False,
               existing_server_default=sa.text("'RUNNING'::character varying"))
    op.alter_column('pipeline_runs', 'pipeline_version',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='Git commit SHA of the ETL code for reproducibility.',
               existing_nullable=True)
    op.drop_index(op.f('ix_pipeline_runs_status_started'), table_name='pipeline_runs', postgresql_where="((status)::text = 'FAILED'::text)")
    op.create_table_comment(
        'pipeline_runs',
        'Audit log of ETL pipeline executions.',
        existing_comment='Operational audit log of every ETL pipeline execution.',
        schema=None
    )
    op.alter_column('salary_ranges', 'salary_midpoint',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment=None,
               existing_comment='Computed column: (min+max)/2. NULL if only one bound present.',
               existing_nullable=True,
               existing_server_default=sa.Computed('\nCASE\n    WHEN ((salary_min IS NOT NULL) AND (salary_max IS NOT NULL)) THEN round(((salary_min + salary_max) / 2.0), 2)\n    ELSE NULL::numeric\nEND', persisted=True))
    op.alter_column('salary_ranges', 'currency_code',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               comment=None,
               existing_comment='ISO 4217 three-letter currency code (must be uppercase).',
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.alter_column('salary_ranges', 'salary_period',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Granularity: HOURLY | DAILY | WEEKLY | MONTHLY | ANNUAL.',
               existing_nullable=False,
               existing_server_default=sa.text("'ANNUAL'::character varying"))
    op.alter_column('salary_ranges', 'is_estimated',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE if the salary was inferred/estimated, not explicitly stated.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('salary_ranges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('salary_ranges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_salary_ranges_midpoint_currency'), table_name='salary_ranges', postgresql_where='(salary_midpoint IS NOT NULL)')
    op.create_table_comment(
        'salary_ranges',
        'Salary information for job postings.',
        existing_comment='Salary information for job postings. Separated from jobs for normalisation and versioning.',
        schema=None
    )
    op.alter_column('skills', 'skill_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Canonical, normalised skill name.',
               existing_nullable=False)
    op.alter_column('skills', 'skill_category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Grouping: Programming Language | Cloud Platform | Database | Framework | Tool | Soft Skill | Methodology',
               existing_nullable=True)
    op.alter_column('skills', 'aliases',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Pipe-separated list of known aliases for ETL normalisation.',
               existing_nullable=True)
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_skills_category'), table_name='skills', postgresql_where='(skill_category IS NOT NULL)')
    op.create_index(op.f('ix_skills_skill_category'), 'skills', ['skill_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_skill_category'), table_name='skills')
    op.create_index(op.f('ix_skills_category'), 'skills', ['skill_category'], unique=False, postgresql_where='(skill_category IS NOT NULL)')
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'aliases',
               existing_type=sa.TEXT(),
               comment='Pipe-separated list of known aliases for ETL normalisation.',
               existing_nullable=True)
    op.alter_column('skills', 'skill_category',
               existing_type=sa.VARCHAR(length=100),
               comment='Grouping: Programming Language | Cloud Platform | Database | Framework | Tool | Soft Skill | Methodology',
               existing_nullable=True)
    op.alter_column('skills', 'skill_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Canonical, normalised skill name.',
               existing_nullable=False)
    op.create_table_comment(
        'salary_ranges',
        'Salary information for job postings. Separated from jobs for normalisation and versioning.',
        existing_comment='Salary information for job postings.',
        schema=None
    )
    op.create_index(op.f('ix_salary_ranges_midpoint_currency'), 'salary_ranges', ['salary_midpoint', 'currency_code', 'salary_period'], unique=False, postgresql_where='(salary_midpoint IS NOT NULL)')
    op.alter_column('salary_ranges', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('salary_ranges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('salary_ranges', 'is_estimated',
               existing_type=sa.BOOLEAN(),
               comment='TRUE if the salary was inferred/estimated, not explicitly stated.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('salary_ranges', 'salary_period',
               existing_type=sa.VARCHAR(length=20),
               comment='Granularity: HOURLY | DAILY | WEEKLY | MONTHLY | ANNUAL.',
               existing_nullable=False,
               existing_server_default=sa.text("'ANNUAL'::character varying"))
    op.alter_column('salary_ranges', 'currency_code',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               comment='ISO 4217 three-letter currency code (must be uppercase).',
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.alter_column('salary_ranges', 'salary_midpoint',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Computed column: (min+max)/2. NULL if only one bound present.',
               existing_nullable=True,
               existing_server_default=sa.Computed('\nCASE\n    WHEN ((salary_min IS NOT NULL) AND (salary_max IS NOT NULL)) THEN round(((salary_min + salary_max) / 2.0), 2)\n    ELSE NULL::numeric\nEND', persisted=True))
    op.create_table_comment(
        'pipeline_runs',
        'Operational audit log of every ETL pipeline execution.',
        existing_comment='Audit log of ETL pipeline executions.',
        schema=None
    )
    op.create_index(op.f('ix_pipeline_runs_status_started'), 'pipeline_runs', ['status', sa.literal_column('started_at DESC')], unique=False, postgresql_where="((status)::text = 'FAILED'::text)")
    op.alter_column('pipeline_runs', 'pipeline_version',
               existing_type=sa.VARCHAR(length=40),
               comment='Git commit SHA of the ETL code for reproducibility.',
               existing_nullable=True)
    op.alter_column('pipeline_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Lifecycle state: RUNNING | SUCCESS | FAILED | PARTIAL.',
               existing_nullable=False,
               existing_server_default=sa.text("'RUNNING'::character varying"))
    op.alter_column('locations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'country_code',
               existing_type=sa.String(length=2),
               type_=sa.CHAR(length=2),
               comment='ISO 3166-1 alpha-2 code. Must be exactly 2 uppercase letters.',
               existing_nullable=False)
    op.alter_column('locations', 'state_code',
               existing_type=sa.VARCHAR(length=10),
               comment='ISO 3166-2 subdivision code (e.g., NY, CA).',
               existing_nullable=True)
    op.create_table_comment(
        'jobs',
        'Central entity table. One row per unique job posting per data source.',
        existing_comment='Central entity. One row per unique job posting per data source.',
        schema=None
    )
    op.drop_index(op.f('ix_jobs_posted_date'), table_name='jobs')
    op.create_index(op.f('ix_jobs_posted_date'), 'jobs', [sa.literal_column('posted_date DESC NULLS LAST')], unique=False)
    op.create_index(op.f('ix_jobs_is_remote_posted_date'), 'jobs', ['is_remote', sa.literal_column('posted_date DESC NULLS LAST')], unique=False, postgresql_where='(is_remote = true)')
    op.create_index(op.f('ix_jobs_canonical_title'), 'jobs', ['canonical_title'], unique=False)
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'posted_date',
               existing_type=sa.DATE(),
               comment='Date the job went live on the source site (not ETL ingestion date).',
               existing_nullable=True)
    op.alter_column('jobs', 'is_remote',
               existing_type=sa.BOOLEAN(),
               comment='TRUE=Remote, FALSE=On-site/Hybrid, NULL=Not specified.',
               existing_nullable=True)
    op.alter_column('jobs', 'canonical_title',
               existing_type=sa.VARCHAR(length=200),
               comment="Standardised title after ETL classification (e.g., 'Data Engineer').",
               existing_nullable=True)
    op.alter_column('jobs', 'job_title',
               existing_type=sa.VARCHAR(length=500),
               comment='Raw normalised title from the source.',
               existing_nullable=False)
    op.alter_column('jobs', 'pipeline_run_id',
               existing_type=sa.INTEGER(),
               comment='FK to pipeline_runs. Tracks which ETL run last wrote this record.',
               existing_nullable=True)
    op.alter_column('jobs', 'source_job_id',
               existing_type=sa.VARCHAR(length=500),
               comment='Unique identifier from the originating source (API ID, URL hash). Part of the business key.',
               existing_nullable=False)
    op.create_table_comment(
        'job_skills',
        'Junction table resolving the many-to-many relationship between jobs and skills.',
        existing_comment='Junction table: many-to-many relationship between jobs and skills.',
        schema=None
    )
    op.create_index(op.f('ix_job_skills_required_skill_id'), 'job_skills', ['skill_id'], unique=False, postgresql_where='(is_required = true)')
    op.alter_column('job_skills', 'extracted_text',
               existing_type=sa.VARCHAR(length=500),
               comment='Raw text fragment from posting used to identify this skill (useful for NLP training data).',
               existing_nullable=True)
    op.alter_column('job_skills', 'proficiency_level',
               existing_type=sa.VARCHAR(length=20),
               comment='Skill proficiency expectation: BEGINNER | INTERMEDIATE | ADVANCED | EXPERT.',
               existing_nullable=True)
    op.alter_column('job_skills', 'is_required',
               existing_type=sa.BOOLEAN(),
               comment='TRUE = explicitly required; FALSE = preferred/nice-to-have.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('experience_levels', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'experience_levels',
        'Controlled vocabulary for experience/seniority level classifications.',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint(op.f('uq_experience_levels_label'), 'experience_levels', ['level_label'], postgresql_nulls_not_distinct=False)
    op.alter_column('experience_levels', 'sort_order',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               comment='Display order: 1=Entry, 2=Mid, 3=Senior, 4=Lead, 5=Executive.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('experience_levels', 'max_years_experience',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('experience_levels', 'min_years_experience',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.add_column('employment_types', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_employment_types_label'), 'employment_types', ['type_label'], postgresql_nulls_not_distinct=False)
    op.alter_column('employment_types', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table_comment(
        'data_sources',
        'Catalog of all external job data sources ingested by the pipeline.',
        existing_comment='Catalog of all external job data sources.',
        schema=None
    )
    op.alter_column('data_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='When FALSE, the ETL pipeline skips this source.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('data_sources', 'source_name',
               existing_type=sa.VARCHAR(length=100),
               comment="Short machine-readable key used in ETL code (e.g., 'adzuna').",
               existing_nullable=False)
    op.create_table_comment(
        'companies',
        'Normalised employer/company dimension.',
        existing_comment='Normalised employer dimension table.',
        schema=None
    )
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False, postgresql_where='(industry IS NOT NULL)')
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp of the most recent update.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp when the row was first inserted.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='TRUE if manually enriched/verified against an authoritative source.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('companies', 'company_size',
               existing_type=sa.VARCHAR(length=20),
               comment='Headcount band. Values: 1-10, 11-50, 51-200, 201-500, 501-1000, 1001-5000, 5001-10000, 10001+',
               existing_nullable=True)
    op.create_table('bridge_job_skill',
    sa.Column('sk_fact_job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sk_skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sk_fact_job_id'], ['fact_jobs.sk_fact_job_id'], name=op.f('fk_bridge_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sk_skill_id'], ['dim_skill.sk_skill_id'], name=op.f('fk_bridge_skill'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sk_fact_job_id', 'sk_skill_id', name=op.f('bridge_job_skill_pkey')),
    comment='Bridge Table: Resolves Many-to-Many relationship between Jobs and Skills.'
    )
    op.create_index(op.f('idx_bridge_skill_id'), 'bridge_job_skill', ['sk_skill_id'], unique=False)
    op.create_table('fact_jobs',
    sa.Column('sk_fact_job_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sk_company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sk_location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sk_posted_date_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pipeline_run_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('work_arrangement', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('salary_min', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_max', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('salary_min <= salary_max', name=op.f('chk_fact_salary')),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source_id'], name=op.f('fk_fact_data_source'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.run_id'], name=op.f('fk_fact_pipeline_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sk_company_id'], ['dim_company.sk_company_id'], name=op.f('fk_fact_company'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sk_location_id'], ['dim_location.sk_location_id'], name=op.f('fk_fact_location'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sk_posted_date_id'], ['dim_date.sk_date_id'], name=op.f('fk_fact_date'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sk_fact_job_id', name=op.f('fact_jobs_pkey')),
    sa.UniqueConstraint('job_id', name=op.f('fact_jobs_job_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Core Fact Table: One row per verified job posting.'
    )
    op.create_index(op.f('idx_fact_jobs_title_salary'), 'fact_jobs', ['job_title'], unique=False, postgresql_include=['salary_min', 'salary_max'])
    op.create_index(op.f('idx_fact_jobs_pipeline_run_id'), 'fact_jobs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('idx_fact_jobs_location_id'), 'fact_jobs', ['sk_location_id'], unique=False)
    op.create_index(op.f('idx_fact_jobs_date_id'), 'fact_jobs', ['sk_posted_date_id'], unique=False)
    op.create_index(op.f('idx_fact_jobs_data_source_id'), 'fact_jobs', ['data_source_id'], unique=False)
    op.create_index(op.f('idx_fact_jobs_company_id'), 'fact_jobs', ['sk_company_id'], unique=False)
    op.create_index(op.f('idx_fact_jobs_active'), 'fact_jobs', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_table('dim_date',
    sa.Column('sk_date_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('day_name', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('day_of_month', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('day_of_year', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('is_weekend', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('week_of_year', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('month_number', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('month_name', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('quarter_number', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('year_number', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('is_holiday', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('holiday_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sk_date_id', name=op.f('dim_date_pkey')),
    sa.UniqueConstraint('full_date', name=op.f('dim_date_full_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Conformed Date Dimension for time-series analytics.'
    )
    op.create_index(op.f('idx_dim_date_ymd'), 'dim_date', ['year_number', 'month_number', 'day_of_month'], unique=False)
    op.create_table('dim_company',
    sa.Column('sk_company_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('company_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sk_company_id', name=op.f('dim_company_pkey')),
    sa.UniqueConstraint('company_name', name=op.f('dim_company_company_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Dimension: Companies hiring. Uses Type 1 SCD (Overwrite).'
    )
    op.create_table('dim_skill',
    sa.Column('sk_skill_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('skill_category', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sk_skill_id', name=op.f('dim_skill_pkey')),
    sa.UniqueConstraint('skill_name', name=op.f('dim_skill_skill_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Dimension: Standardised Skills. Uses Type 1 SCD (Overwrite).'
    )
    op.create_table('dim_location',
    sa.Column('sk_location_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location_raw', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('is_remote', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sk_location_id', name=op.f('dim_location_pkey')),
    sa.UniqueConstraint('location_raw', name=op.f('dim_location_location_raw_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Dimension: Job Locations. Uses Type 1 SCD (Overwrite).'
    )
    op.create_index(op.f('idx_dim_location_remote'), 'dim_location', ['is_remote', 'city'], unique=False)
    # ### end Alembic commands ###
